// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4iUijEp9uQvrC-BfddLZxVtkyDOH30Dk',
    appId: '1:760491253033:web:cc4ce32ee823e5974aab38',
    messagingSenderId: '760491253033',
    projectId: 'my-crm-bansal',
    authDomain: 'my-crm-bansal.firebaseapp.com',
    storageBucket: 'my-crm-bansal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAvqXDESzQfektjnoVSicYP3tg8p9JRU',
    appId: '1:760491253033:android:5a17e2ab2eb6bf334aab38',
    messagingSenderId: '760491253033',
    projectId: 'my-crm-bansal',
    storageBucket: 'my-crm-bansal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQwHj3ud9OlSkiujjZhtDGCf9JnYfVRTo',
    appId: '1:760491253033:ios:03c3263e1e81bb914aab38',
    messagingSenderId: '760491253033',
    projectId: 'my-crm-bansal',
    storageBucket: 'my-crm-bansal.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQwHj3ud9OlSkiujjZhtDGCf9JnYfVRTo',
    appId: '1:760491253033:ios:03c3263e1e81bb914aab38',
    messagingSenderId: '760491253033',
    projectId: 'my-crm-bansal',
    storageBucket: 'my-crm-bansal.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4iUijEp9uQvrC-BfddLZxVtkyDOH30Dk',
    appId: '1:760491253033:web:0c3c42e47e8a584d4aab38',
    messagingSenderId: '760491253033',
    projectId: 'my-crm-bansal',
    authDomain: 'my-crm-bansal.firebaseapp.com',
    storageBucket: 'my-crm-bansal.firebasestorage.app',
  );
}
